import { useState } from 'react'
import { Button, Card, PageHeader, Progress } from '../components/UI'

const questions=['Tell me about a project where you used data to solve a problem.','What is the difference between INNER JOIN and LEFT JOIN?','How would you handle missing values in a dataset?']
export default function Interview(){
 const [started,setStarted]=useState(false); const [i,setI]=useState(0); const [done,setDone]=useState(false)
 if(done)return <><PageHeader title="Interview Evaluation" subtitle="Feedback based on observable characteristics of your mock answers."/><div className="metric-grid">{[['Technical Correctness',74],['Relevance',82],['Clarity',78],['Communication',76]].map(([x,v])=><Card key={x as string}><small>{x}</small><div className="metric">{v}%</div><Progress value={v as number}/></Card>)}</div><Card><h2>Recommended practice</h2><ul><li>Structure technical answers with a clear approach and example.</li><li>Explain trade-offs rather than giving only definitions.</li><li>Practice concise project explanations using your actual work.</li></ul></Card></>
 if(!started)return <><PageHeader title="Interview Preparation" subtitle="Configure a mock interview based on your target role."/><Card><div className="form-grid"><label>Target Role<select><option>Junior Data Analyst</option><option>Frontend Developer</option></select></label><label>Interview Type<select><option>Mixed</option><option>Technical</option><option>HR</option><option>Resume-Based</option></select></label><label>Difficulty<select><option>Medium</option><option>Easy</option><option>Hard</option></select></label><label>Questions<select><option>3</option><option>5</option><option>10</option></select></label></div><Button onClick={()=>setStarted(true)}>Start Mock Interview</Button></Card></>
 return <><PageHeader title="Mock Interview" subtitle="Junior Data Analyst · Mixed · Medium"/><Card><div className="section-title"><b>Question {i+1} of {questions.length}</b><span>{Math.round((i+1)/questions.length*100)}%</span></div><Progress value={(i+1)/questions.length*100}/><h2 className="question">{questions[i]}</h2><textarea rows={7} placeholder="Type your answer here..."/><div className="actions"><Button variant="secondary">Submit Answer</Button>{i<questions.length-1?<Button onClick={()=>setI(i+1)}>Next Question</Button>:<Button onClick={()=>setDone(true)}>End Interview</Button>}</div></Card></>
}