import { LineChart, Line, ResponsiveContainer, XAxis, YAxis, Tooltip, RadarChart, Radar, PolarGrid, PolarAngleAxis } from 'recharts'
import { Card, PageHeader, Progress } from '../components/UI'

export function ProgressPage(){
 const trend=[{week:'W1',score:52},{week:'W2',score:58},{week:'W3',score:64},{week:'W4',score:69},{week:'W5',score:74}]
 const radar=[{area:'Resume',v:78},{area:'Skills',v:70},{area:'Projects',v:82},{area:'Interview',v:71},{area:'Roadmap',v:65}]
 return <><PageHeader title="Progress & Analytics" subtitle="Demo progress data showing how preparation could be tracked over time."/><div className="two-col"><Card><h2>Readiness Trend</h2><div className="chart"><ResponsiveContainer width="100%" height={260}><LineChart data={trend}><XAxis dataKey="week"/><YAxis domain={[0,100]}/><Tooltip/><Line dataKey="score"/></LineChart></ResponsiveContainer></div></Card><Card><h2>Preparation Coverage</h2><div className="chart"><ResponsiveContainer width="100%" height={260}><RadarChart data={radar}><PolarGrid/><PolarAngleAxis dataKey="area"/><Radar dataKey="v"/></RadarChart></ResponsiveContainer></div></Card></div></>
}
export function Report(){
 const rows=[['Resume',78],['Technical Skills',70],['Projects',82],['Interview',71],['Communication',76],['Skill Coverage',68],['Roadmap Progress',65]]
 return <><PageHeader title="Final Placement Readiness Report" subtitle="A consolidated view of your current preparation — not a guarantee of placement."/><Card><h2>Candidate Summary</h2><p>Computer Science student building strengths across web development, Python and data-oriented skills. Current preparation is strongest in projects and resume structure, with clear opportunities in advanced SQL, statistics and interview depth.</p></Card><div className="card-grid">{rows.map(([x,v])=><Card key={x as string}><div className="section-title"><h3>{x}</h3><b>{v}%</b></div><Progress value={v as number}/></Card>)}</div><div className="two-col"><Card><h2>Strengths</h2><ul><li>Relevant technical project experience</li><li>Good foundational programming skills</li><li>Consistent learning roadmap</li></ul></Card><Card><h2>Recommended Next Actions</h2><ol><li>Complete advanced SQL practice.</li><li>Build one analytics portfolio project.</li><li>Run two role-specific mock interviews.</li><li>Review and approve resume improvements.</li></ol></Card></div></>
}
export function Settings(){return <><PageHeader title="Settings" subtitle="Manage frontend demo preferences."/><Card><h2>Preferences</h2><label>Notifications<select><option>Enabled</option><option>Disabled</option></select></label><label>Appearance<select><option>System</option><option>Light</option><option>Dark</option></select></label><p className="notice">These settings are UI-only in the current frontend prototype.</p></Card></>}
