import { useState } from 'react'
import { Badge, Button, Card, PageHeader, Progress } from '../components/UI'
import { UploadCloud, WandSparkles } from 'lucide-react'

export default function Resume(){
 const [tab,setTab]=useState<'upload'|'analysis'|'builder'>('upload')
 return <><PageHeader title="Resume" subtitle="Upload, analyze and improve your resume for target roles."/>
 <div className="tabs">{(['upload','analysis','builder'] as const).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t==='builder'?'Builder / Optimizer':t[0].toUpperCase()+t.slice(1)}</button>)}</div>
 {tab==='upload'&&<Card><div className="drop"><UploadCloud size={42}/><h2>Upload your resume</h2><p>PDF or DOCX · Mock upload for frontend prototype</p><input type="file" accept=".pdf,.doc,.docx"/><Button>Analyze Resume</Button></div></Card>}
 {tab==='analysis'&&<div className="two-col"><Card><h2>Overall Resume Score</h2><div className="score">78</div><Progress value={78}/><p>Strong project exposure. Improve role-specific keywords and measurable impact.</p></Card><Card><h2>Strengths</h2><ul><li>Clear technical skills</li><li>Relevant academic projects</li><li>Good education section</li></ul><h2>Areas to improve</h2><ul><li>Add measurable project outcomes</li><li>Strengthen professional summary</li><li>Use more role-relevant keywords</li></ul></Card><Card><h2>Detected Skills</h2><div className="badges">{['Python','SQL','React','JavaScript','HTML','CSS'].map(x=><Badge key={x}>{x}</Badge>)}</div></Card><Card><h2>Recommended Keywords</h2><div className="badges">{['REST APIs','Data Analysis','Git','Problem Solving'].map(x=><Badge key={x}>{x}</Badge>)}</div></Card></div>}
 {tab==='builder'&&<div className="two-col"><Card><h2>Resume Builder</h2><label>Professional Summary<textarea defaultValue="Computer Science student with experience building web and data-focused academic projects."/></label><label>Project Description<textarea defaultValue="Built a responsive placement preparation dashboard using React and TypeScript."/></label><div className="actions"><Button variant="secondary"><WandSparkles size={16}/> Improve Summary</Button><Button>Save</Button></div><p className="notice">AI suggestions should be reviewed by the student. PrepMate should improve wording only and must not invent experience, skills, achievements or metrics.</p></Card><Card><h2>Live Preview</h2><div className="resume-preview"><h2>Aarohi Sharma</h2><p>Computer Science Student</p><hr/><h3>Summary</h3><p>Computer Science student with experience building web and data-focused academic projects.</p><h3>Skills</h3><p>Python · SQL · React · JavaScript</p><h3>Projects</h3><strong>PrepMate AI</strong><p>Placement preparation platform with profile, resume, career and interview modules.</p></div></Card></div>}
 </>
}